### ISSUE TITLE
Create Login with Email form view

### ISSUE THREAD

**Issue by emelleme** [emelleme-prishtina/flutter-samples#1]

**Comment by emelleme** [comment]
How is this task going?

**Comment by shejza** [comment]
@emelleme Good I connected login with firebase and its working very good I am having trouble with git I will fix it and make a commit

**Comment by shejza** [comment]
I finished creating login with email form view I also connected it with firebase, You can add manually a user on firebase and test it you will see on console  if you log in or you can see it on the firebase to the console /authentication/users   to the Signed in column it tells you the date when you login.
